version: "3.9"

networks:
  smarthome-net:
    driver: bridge

services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    networks:
      - smarthome-net
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=dragonflare2105
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=smarthome
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - smarthome-net
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=dragonflare2105
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    networks:
      - smarthome-net
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # optional: WebSocket MQTT
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  influxdb-data:
